# Generated by Django 5.2 on 2025-05-23 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_invoice_invoiceitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="contract",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="core.contract",
            ),
        ),
    ]
